<<<<<<< HEAD
# Generated by Django 3.1.1 on 2020-10-14 22:06

from django.db import migrations, models
=======
# Generated by Django 3.1.1 on 2020-11-05 04:08

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> da0415a60300b6897e471a8066325abf95bfd55e


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='template',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('shortDescription', models.CharField(max_length=100)),
                ('contentTemp', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('published', models.BooleanField()),
=======
            name='Emailtemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortDescription', models.CharField(max_length=100)),
                ('contentTemp', models.TextField()),
                ('subject', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('published', models.BooleanField(default=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=5)),
                ('published', models.BooleanField(default=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('emailtemplates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=5)),
                ('party', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('emailtemplates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.emailtemplate')),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.issue')),
                ('representatives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.representative')),
>>>>>>> da0415a60300b6897e471a8066325abf95bfd55e
            ],
        ),
    ]
