# Generated by Django 3.1.1 on 2020-10-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='template',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('shortDescription', models.CharField(max_length=100)),
                ('contentTemp', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('published', models.BooleanField()),
            ],
        ),
    ]
