# Generated by Django 3.1.1 on 2020-10-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='published',
        ),
    ]
