# Generated by Django 3.1.1 on 2020-11-04 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=5)),
                ('published', models.BooleanField(default=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=5)),
                ('party', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.issue')),
                ('representatives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.representative')),
            ],
        ),
        migrations.DeleteModel(
            name='template',
        ),
    ]
