# Generated by Django 3.1.1 on 2020-11-05 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
