# Generated by Django 3.1.1 on 2020-10-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emailtemplate',
        ),
    ]
