# Generated by Django 3.1.1 on 2020-11-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
