# Generated by Django 3.1.1 on 2020-10-21 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0002_delete_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailtemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortDescription', models.CharField(max_length=100)),
                ('contentTemp', models.TextField()),
                ('subject', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('user', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
