# Generated by Django 3.1.1 on 2020-11-05 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_remove_emailtemplate_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
