# Generated by Django 3.1.1 on 2020-10-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_remove_template_published'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='template',
            new_name='Emailtemplate',
        ),
    ]
