# Generated by Django 3.1.1 on 2020-11-04 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20201104_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailtemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortDescription', models.CharField(max_length=100)),
                ('contentTemp', models.TextField()),
                ('subject', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('published', models.BooleanField(default=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='emailtemplates',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='masterdata.emailtemplate'),
            preserve_default=False,
        ),
    ]
