# Generated by Django 3.1.1 on 2020-11-04 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20201104_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='emailtemplates',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='masterdata.emailtemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
