# Generated by Django 3.1.1 on 2020-11-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20201104_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
