# Generated by Django 3.1.1 on 2020-11-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_delete_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='issues',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
