# Generated by Django 3.1.1 on 2020-11-05 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_auto_20201105_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=5)),
                ('published', models.BooleanField(default=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('emailtemplates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.emailtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='issues',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='masterdata.issue'),
            preserve_default=False,
        ),
    ]
