# Generated by Django 3.1.1 on 2020-10-30 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_emailtemplate_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
