# Generated by Django 3.1.1 on 2020-11-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_auto_20201105_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='emailtemplates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='client',
            name='representatives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.representative'),
        ),
    ]
