# Generated by Django 3.1.1 on 2020-10-31 18:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_auto_20201030_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=5)),
                ('party', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=5)),
                ('published', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('emailtemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.emailtemplate')),
            ],
        ),
    ]
