# Generated by Django 3.1.1 on 2020-11-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_auto_20201105_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='issues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.issue'),
        ),
    ]
