# Generated by Django 3.1.1 on 2020-10-30 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_auto_20201030_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=5)),
                ('published', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
