# Generated by Django 3.1.1 on 2020-10-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_issues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
    ]
