# Generated by Django 3.1.1 on 2020-10-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_auto_20201030_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='party',
            field=models.CharField(default='tea', max_length=50),
            preserve_default=False,
        ),
    ]
