# Generated by Django 3.1.1 on 2020-11-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_auto_20201105_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='emailtemplates',
        ),
        migrations.AddField(
            model_name='client',
            name='favorites',
            field=models.ManyToManyField(to='masterdata.Emailtemplate'),
        ),
    ]
