# Generated by Django 3.1.1 on 2020-10-30 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_representative_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masterdata.issue'),
        ),
    ]
