# Generated by Django 3.1.1 on 2020-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_client_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='District',
            field=models.CharField(default='', max_length=5),
        ),
    ]
