# Generated by Django 3.1.1 on 2020-10-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_emailtemplate_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='issue',
            field=models.ForeignKey(default='ec477b08-ad80-4fdc-a6e5-0f5f383aeebb', on_delete=django.db.models.deletion.CASCADE, to='masterdata.issue'),
        ),
    ]
