# Generated by Django 3.1.1 on 2020-10-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_auto_20201030_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='issue',
        ),
    ]
