# Generated by Django 3.1.1 on 2020-10-30 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_remove_emailtemplate_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='issue',
            field=models.ForeignKey(default='ec477b08ad804fdca6e50f5f383aeebb', on_delete=django.db.models.deletion.CASCADE, to='masterdata.issue'),
        ),
    ]
