# Generated by Django 3.1.1 on 2020-10-30 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_emailtemplate_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='issue',
        ),
    ]
